### PR TITLE
OS X build support

### PR DESCRIPTION
**Pull request by JanSimek**
Hello Vasiliy, I added a quick and dirty fix for OS X build and crash that I experienced in the menu. It needs to be properly fixed and cleaned, but I had spent a lot of time on just getting it to compile, so I wanted to run it ASAP.

I experience a lot of different crashes and bugs (e.g. menu widgets are broken, cannot shoot, physics related crash in Survivor, etc.), do you think it is something you could have introduced or was it like that from the start when the source code was released by Frozenbyte?

Thanks for the work you've done.

### CODE REVIEW

**Comment by vayerx** [comment]
Hello Jan,

Thank you for fixes -- I'll have a look at the weekend.
There were lots of crashes from the very beginning. Some of them came out during porting to amd64.
I introduced several bugs myself by migrating to cmake build (initial gmake-based build system didn't worked for me at all). But I hope that I've fixed most of them.

**Comment by JanSimek** [comment]
Oh hell, it merged my whole repo instead of just the relevant commits. You don't want that. Sorry, my mistake.

**Comment by vayerx** [comment]
I excluded commit `Revert "Use SDL_sound instead of libvorbisfile"` -- I'll try to reproduce it and maybe fix it.

**Comment by JanSimek** [comment]
All right then.

**Pull request merged**
