### PR TITLE
FFMPEG 6 + Cmake deprecation updates

### PR DESCRIPTION
**Pull request by thearchivalone**
I know there hasn't been that much activity in the main repository over the past few years, but I've gotten the code to build and run successfully on FreeBSD 14.0 with Clang17 using minimum changes. The only real major library deprecations were with FFMpeg, most of which should compile on FFMpeg 5 (not sure about 4) if anyone needs the older versions supported. I also removed FindGLEW.cmake since that now is one of the default modules in modern CMake releases.

### CODE REVIEW

**Comment by thearchivalone** [comment]
Accidentally forgot to update the top level CMakeLists.txt to use the proper GLEW variables.

**Comment by JanSimek** [comment]
I tried to compile this branch and it seems one more fix will need to be added for FFMPEG 7 compatibility:

```
shadowgrounds/storm/storm3dv2/treader.cpp:145:65: error: ‘struct AVCodecContext’ has no member named ‘channels’
  145 |                     builder->setStereo(mContext->audiocodecctx->channels);
```

I guess something like this: https://github.com/darlinghq/darling/pull/1537/files

It is a shame this engine was abandoned. I really enjoyed the game.

**Comment by thearchivalone** [comment]
> I tried to compile this branch and it seems one more fix will need to be added for FFMPEG 7 compatibility:
> 
> ```
> shadowgrounds/storm/storm3dv2/treader.cpp:145:65: error: ‘struct AVCodecContext’ has no member named ‘channels’
>   145 |                     builder->setStereo(mContext->audiocodecctx->channels);
> ```
> 
> I guess something like this: https://github.com/darlinghq/darling/pull/1537/files
> 
> It is a shame this engine was abandoned. I really enjoyed the game.

That compiles correctly on FFMPEG 6, so I'll add it. Thanks

**Comment by thearchivalone** [comment]
That should fix it. Might as well make FFMPEG 6 the baseline minimum required version now. I played the game quite a bit back in the day, too, although this source release has some major bugs (one of which being no assets load properly once you get past the main menu screen)

**Comment by vayerx** [comment]
@bedwardly-down,
Thanks for PR!
I found that I have some local commits from 2014 (omg). I'm trying to resolve conflicts and fix build. I'll do my best to merge your PR as soon as possible.

**Comment by samrocketman** [comment]
Thanks for this patch @thearchivalone ! I haven't contributed to this repo before but I love this game :D

**Pull request closed without merging**
